export const products = [
    {
        id: 1,
        name: "Wireless Headphones",
        category: "Electronics",
        brand: "Brand A",
        price: 99.99,
        rating: 4.5,
        imageUrl: "https://example.com/images/headphones.jpg",
    },
    {
        id: 2,
        name: "Bluetooth Speaker",
        category: "Electronics",
        brand: "Brand B",
        price: 49.99,
        rating: 4.0,
        imageUrl: "https://example.com/images/speaker.jpg",
    },
    {
        id: 3,
        name: "Running Shoes",
        category: "Footwear",
        brand: "Brand C",
        price: 59.99,
        rating: 4.2,
        imageUrl: "https://example.com/images/shoes.jpg",
    },
    {
        id: 4,
        name: "Smartphone",
        category: "Electronics",
        brand: "Brand D",
        price: 499.99,
        rating: 4.8,
        imageUrl: "https://example.com/images/smartphone.jpg",
    },
    {
        id: 5,
        name: "Leather Jacket",
        category: "Clothing",
        brand: "Brand E",
        price: 199.99,
        rating: 4.7,
        imageUrl: "https://example.com/images/jacket.jpg",
    },
];
